<h1> CS506 Programming for Computing </h1>
<h2> Pytorch Tutorial </h2>
<h3> Team Members: Sukhmani Thukral,  Lanxi Luo, Shruti Arvind Kherade <h3>

This tutorial provides a comprehensive guide to using PyTorch for image classification on the MNIST dataset. You'll learn how to work with tensors, load and transform data, define neural networks, and train models using `torch.autograd`. The MNIST dataset consists of 70,000 grayscale images of handwritten digits (0–9), each of size 28x28 pixels.

Topics we will cover:
- Introduction to PyTorch and its Applications
- Tensors
- Autograd and Gradients
- Datasets and Data Loading
- Transforms
- Brief Introduction to Neural Network
- Building Neural Network
- Training Neural Network using torch.autograd

# (1) Introduction to PyTorch and its Applications

PyTorch is a popular open-source deep learning framework developed by Facebook's AI Research lab. It provides a flexible and efficient platform for building and training neural networks, making it popular among researchers and practitioners in machine learning and artificial intelligence.

## Key Features of PyTorch
- **Dynamic Computation Graphs:** PyTorch uses dynamic computation graphs (also known as define-by-run), allowing for more flexibility during model development and debugging.
- **Tensor Computation:** PyTorch offers a powerful N-dimensional array (tensor) library, similar to NumPy, with strong GPU acceleration.
- **Automatic Differentiation:** The `autograd` module automatically computes gradients, simplifying the process of backpropagation in neural networks.
- **Extensive Libraries:** PyTorch includes libraries for vision (`torchvision`), text (`torchtext`), and audio (`torchaudio`) tasks.

## Applications of PyTorch
PyTorch is widely used in various domains, including:
- **Computer Vision:** Image classification, object detection, segmentation, and style transfer.
- **Natural Language Processing (NLP):** Text classification, sentiment analysis, machine translation, and language modeling.
- **Reinforcement Learning:** Training agents for games, robotics, and decision-making tasks.
- **Generative Models:** Building GANs (Generative Adversarial Networks) and VAEs (Variational Autoencoders).
- **Scientific Computing:** Simulations, time-series forecasting, and other research applications.

PyTorch's ease of use, strong community support, and integration with Python make it a preferred choice for both academic research and industry applications.

## (2) Tensors
Tensors are the fundamental data structures in PyTorch, similar to NumPy arrays but with powerful GPU acceleration and gradient tracking capabilities.

### Tensor Creation
You can create tensors from Python lists or using built-in PyTorch methods.

In [2]:
import torch

# Creating tensors
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])
print("Tensor a:", a)
print("Tensor b:", b)

Tensor a: tensor([1., 2., 3.])
Tensor b: tensor([4., 5., 6.])


### Arithmetic Operations
Tensors support standard arithmetic operations like addition, subtraction, multiplication, and dot product.

In [3]:
print("Addition:", a + b)
print("Dot product:", torch.dot(a, b))

Addition: tensor([5., 7., 9.])
Dot product: tensor(32.)


### Shape and Data Types
Tensors have attributes for checking their shape and data types.

In [4]:
print("Shape of a:", a.shape)
print("Data type of a:", a.dtype)

Shape of a: torch.Size([3])
Data type of a: torch.float32


## (3) Autograd and Gradients
PyTorch uses `autograd` to automatically compute gradients. This is useful for training neural networks using backpropagation.

### requires_grad
To track operations on tensors for automatic differentiation, set `requires_grad=True`.

In [5]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y = torch.tensor([4.0, 5.0, 6.0], requires_grad=True)

### .backward()
Computes the gradients of a scalar output with respect to input tensors.

In [ ]:
z = torch.dot(x, y)
z.backward()

### Accessing .grad
Once `.backward()` is called, you can access the gradient using the `.grad` attribute.

In [6]:
print("Gradient of x:", x.grad)

Gradient of x: None


In [7]:
import torch

# Introduction to Tensors


# Tensors are multi-dimensional arrays, similar to NumPy arrays, but with GPU acceleration and automatic differentiation support.
# Example: Creating a 1D tensor
tensor_1d = torch.tensor([1.0, 2.0, 3.0])
print("1D Tensor:", tensor_1d)

# Example: Creating a 2D tensor (matrix)
tensor_2d = torch.tensor([[1, 2], [3, 4]])
print("2D Tensor:\n", tensor_2d)

# Tensors can be created from lists, NumPy arrays, or using built-in functions like torch.zeros, torch.ones, etc.
tensor_zeros = torch.zeros((2, 3))
print("Tensor of zeros:\n", tensor_zeros)

tensor_ones = torch.ones((2, 3))
print("Tensor of ones:\n", tensor_ones)

# Tensors support various operations: addition, multiplication, reshaping, etc.
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print("Addition:", a + b)
print("Element-wise multiplication:", a * b)

1D Tensor: tensor([1., 2., 3.])
2D Tensor:
 tensor([[1, 2],
        [3, 4]])
Tensor of zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Tensor of ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Addition: tensor([5, 7, 9])
Element-wise multiplication: tensor([ 4, 10, 18])


## (4) Datasets and Data Loading
PyTorch uses `torchvision.datasets` and `DataLoader` to handle data.

In [1]:
!pip install torchvision
from torchvision import datasets
from torch.utils.data import DataLoader
from torchvision.transforms import ToTensor

train_data = datasets.MNIST(root="data", train=True, download=True, transform=ToTensor())
test_data = datasets.MNIST(root="data", train=False, download=True, transform=ToTensor())

train_loader = DataLoader(train_data, batch_size=64, shuffle=True)
test_loader = DataLoader(test_data, batch_size=64, shuffle=False)


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python3 -m pip install --upgrade pip


100.0%
100.0%
100.0%
100.0%


## (5) Transforms
We normalize the dataset to have zero mean and unit variance. This helps the network converge faster.

In [5]:
%pip install torchvision

from torchvision import transforms
from torchvision import datasets
from torch.utils.data import DataLoader



transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])

train_data = datasets.MNIST(root="data", train=True, download=True, transform=transform)
test_data = datasets.MNIST(root="data", train=False, download=True, transform=transform)

train_loader = DataLoader(train_data, batch_size=64, shuffle=True)
test_loader = DataLoader(test_data, batch_size=64, shuffle=False)


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [ ]:


import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

# Step 2: Load the animal dataset 

data = {
    'Animal': ['cat', 'dog', 'rabbit', 'cat', 'dog', 'rabbit', 'cat', 'dog', 'rabbit'],
    'Weight': [4, 20, 2, 5, 22, 2.5, 4.5, 21, 3],
    'Color': ['black', 'brown', 'white', 'white', 'black', 'brown', 'brown', 'white', 'black']
}
df = pd.DataFrame(data)
print("Sample Data:")
print(df)

# Step 3: Encode categorical variables
le_color = LabelEncoder()
df['Color_encoded'] = le_color.fit_transform(df['Color'])
le_animal = LabelEncoder()
df['Animal_encoded'] = le_animal.fit_transform(df['Animal'])

# Step 4: Prepare features and target
X = df[['Weight', 'Color_encoded']]
y = df['Animal_encoded']

# Step 5: Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Step 6: Train a classifier
clf = RandomForestClassifier(random_state=42)
clf.fit(X_train, y_train)

# Step 7: Make predictions and evaluate
y_pred = clf.predict(X_test)
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=le_animal.classes_))

# Explanation:
# - We created a sample animal dataset with features 'Weight' and 'Color'.
# - Used LabelEncoder to convert categorical data to numeric.
# - Split the data into training and testing sets.
# - Trained a RandomForestClassifier for multi-class classification.
# - Evaluated the model using a classification report.

Sample Data:
   Animal  Weight  Color
0     cat     4.0  black
1     dog    20.0  brown
2  rabbit     2.0  white
3     cat     5.0  white
4     dog    22.0  black
5  rabbit     2.5  brown
6     cat     4.5  brown
7     dog    21.0  white
8  rabbit     3.0  black

Classification Report:
              precision    recall  f1-score   support

         cat       0.00      0.00      0.00         0
         dog       0.00      0.00      0.00         2
      rabbit       1.00      1.00      1.00         1

    accuracy                           0.33         3
   macro avg       0.33      0.33      0.33         3
weighted avg       0.33      0.33      0.33         3



/home/codespace/.local/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/codespace/.local/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/codespace/.local/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/codespace/.loca

Pytorch for Natural Language Processing

In [6]:
import torch

import torch.nn as nn
import torch.optim as optim

# Example: Simple sentiment classification with PyTorch

# Sample data (toy example)
sentences = ["I love PyTorch", "PyTorch is great", "I dislike bugs", "Bugs are annoying"]
labels = [1, 1, 0, 0]  # 1: positive, 0: negative

# Build vocabulary
vocab = set(word for sent in sentences for word in sent.lower().split())
word2idx = {word: idx for idx, word in enumerate(vocab)}

# Encode sentences as bag-of-words vectors
def encode(sentence):
    vec = torch.zeros(len(vocab))
    for word in sentence.lower().split():
        vec[word2idx[word]] += 1
    return vec

X = torch.stack([encode(s) for s in sentences])
y = torch.tensor(labels, dtype=torch.float32).unsqueeze(1)

# Simple model
model = nn.Sequential(
    nn.Linear(len(vocab), 1),
    nn.Sigmoid()
)

criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Training loop
for epoch in range(100):
    optimizer.zero_grad()
    output = model(X)
    loss = criterion(output, y)
    loss.backward()
    optimizer.step()

print("Trained model predictions:", (model(X) > 0.5).int().squeeze().tolist())

Trained model predictions: [1, 1, 0, 0]


In [8]:
import torch.nn as nn

# Create an embedding layer for the vocabulary
embedding_dim = 5  # You can choose any embedding size
embedding = nn.Embedding(num_embeddings=len(vocab), embedding_dim=embedding_dim)

# Example: Get embeddings for each word in a sentence
sample_sentence = sentences[0].lower().split()  # e.g., "I love PyTorch"
indices = torch.tensor([word2idx[word] for word in sample_sentence])

embedded_words = embedding(indices)
print("Word embeddings for '{}':\n{}".format(sample_sentence, embedded_words))

Word embeddings for '['i', 'love', 'pytorch']':
tensor([[ 1.2678,  0.8066, -0.6511,  0.9877,  0.0681],
        [ 1.1497, -0.2470, -1.0230, -0.3671,  3.0108],
        [ 0.0067, -1.2524,  0.7639,  1.0786,  0.7947]],
       grad_fn=<EmbeddingBackward0>)


In [ ]:
import torch.nn as nn

# Define a simple feedforward neural network for NLP (Bag-of-Words input)
class SimpleNLPModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim):
        super(SimpleNLPModel, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.fc = nn.Linear(embedding_dim, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, x):
        # x: (batch_size, seq_len)
        embedded = self.embedding(x)  # (batch_size, seq_len, embedding_dim)
        pooled = embedded.mean(dim=1)  # Average pooling over sequence
        out = self.fc(pooled)
        return self.sigmoid(out)



In [10]:
# Example usage:
model = SimpleNLPModel(vocab_size=len(vocab), embedding_dim=embedding_dim)
output = model(indices.unsqueeze(0))  # indices: tensor of word indices for a sentence
print("Model output:", output)

Model output: tensor([[0.6169]], grad_fn=<SigmoidBackward0>)


In [11]:
import torch

import torch.nn as nn

# Example LSTM-based sentiment analysis model
class SentimentLSTM(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(SentimentLSTM, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, output_dim)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, x):
        embedded = self.embedding(x)  # (batch, seq_len, embedding_dim)
        lstm_out, _ = self.lstm(embedded)  # (batch, seq_len, hidden_dim)
        out = lstm_out[:, -1, :]  # Take the output of the last time step
        out = self.fc(out)
        return self.sigmoid(out)

# Prepare input: convert sentences to sequences of word indices
max_len = max(len(s.split()) for s in sentences)
def encode_sequence(sentence, word2idx, max_len):
    idxs = [word2idx[word] for word in sentence.lower().split()]
    # Pad with zeros if shorter than max_len
    idxs += [0] * (max_len - len(idxs))
    return torch.tensor(idxs)

X_seq = torch.stack([encode_sequence(s, word2idx, max_len) for s in sentences])
y_seq = torch.tensor(labels, dtype=torch.float32).unsqueeze(1)

# Instantiate and train the model
hidden_dim = 8
output_dim = 1
lstm_model = SentimentLSTM(vocab_size=len(vocab), embedding_dim=embedding_dim, hidden_dim=hidden_dim, output_dim=output_dim)
lstm_criterion = nn.BCELoss()
lstm_optimizer = torch.optim.Adam(lstm_model.parameters(), lr=0.01)

for epoch in range(100):
    lstm_optimizer.zero_grad()
    outputs = lstm_model(X_seq)
    loss = lstm_criterion(outputs, y_seq)
    loss.backward()
    lstm_optimizer.step()

print("LSTM model predictions:", (lstm_model(X_seq) > 0.5).int().squeeze().tolist())

LSTM model predictions: [1, 1, 0, 0]


In [12]:
import re

def preprocess_text(text):
    # Lowercase
    text = text.lower()
    # Remove punctuation and non-alphabetic characters
    text = re.sub(r'[^a-z\s]', '', text)
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    return text

# Example: preprocess all sentences
preprocessed_sentences = [preprocess_text(s) for s in sentences]
print(preprocessed_sentences)

['i love pytorch', 'pytorch is great', 'i dislike bugs', 'bugs are annoying']


In [13]:
# Text Preprocessing Explanation

# Text preprocessing is a crucial step in Natural Language Processing (NLP) tasks.
# It typically includes:
# 1. Cleaning: Removing punctuation, converting text to lowercase, and eliminating unwanted characters.
# 2. Tokenization: Splitting sentences into individual words or tokens.
# 3. Vectorization: Converting words or tokens into numerical representations (such as indices or embeddings) that can be used by machine learning models.

# Example using the preprocess_text function and tokenization:
for sentence in sentences:
    cleaned = preprocess_text(sentence)
    tokens = cleaned.split()
    print(f"Original: {sentence}")
    print(f"Cleaned: {cleaned}")
    print(f"Tokens: {tokens}\n")

Original: I love PyTorch
Cleaned: i love pytorch
Tokens: ['i', 'love', 'pytorch']

Original: PyTorch is great
Cleaned: pytorch is great
Tokens: ['pytorch', 'is', 'great']

Original: I dislike bugs
Cleaned: i dislike bugs
Tokens: ['i', 'dislike', 'bugs']

Original: Bugs are annoying
Cleaned: bugs are annoying
Tokens: ['bugs', 'are', 'annoying']



In [14]:
# Standardize the token lengths of each review for consistency

# Find the maximum sequence length
max_seq_len = max(len(s.split()) for s in sentences)

# Function to encode and pad/truncate each sentence to max_seq_len
def encode_and_pad(sentence, word2idx, max_len):
    idxs = [word2idx[word] for word in sentence.lower().split()]
    # Pad with zeros if shorter, or truncate if longer
    if len(idxs) < max_len:
        idxs += [0] * (max_len - len(idxs))
    else:
        idxs = idxs[:max_len]
    return torch.tensor(idxs)

# Apply to all sentences
X_padded = torch.stack([encode_and_pad(s, word2idx, max_seq_len) for s in sentences])
print("Padded input tensor:\n", X_padded)

Padded input tensor:
 tensor([[3, 0, 5],
        [5, 7, 1],
        [3, 6, 4],
        [4, 2, 8]])


In [15]:
import torch.nn as nn

class SentimentLSTM(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(SentimentLSTM, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, output_dim)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, x):
        embedded = self.embedding(x)  # (batch, seq_len, embedding_dim)
        lstm_out, _ = self.lstm(embedded)  # (batch, seq_len, hidden_dim)
        out = lstm_out[:, -1, :]  # Take the output of the last time step
        out = self.fc(out)
        return self.sigmoid(out)

In [20]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from torch.utils.data import DataLoader, TensorDataset
from torchvision import datasets, transforms

# Define dataset transformation
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])

# Load MNIST dataset
train_data = datasets.MNIST(root="data", train=True, download=True, transform=transform)
test_data = datasets.MNIST(root="data", train=False, download=True, transform=transform)

train_loader = DataLoader(train_data, batch_size=64, shuffle=True)
test_loader = DataLoader(test_data, batch_size=64, shuffle=False)

# Define the NLP model
class SimpleNLPModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(SimpleNLPModel, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, output_dim)
        self.sigmoid = nn.Sigmoid()  # Required for BCELoss

    def forward(self, x):
        x = self.embedding(x.long())  # Ensure LongTensor for embedding lookup
        x, _ = self.lstm(x)
        x = self.fc(x[:, -1, :])
        return self.sigmoid(x)

# Initialize model, loss function

In [21]:
# Model Evaluation

# Evaluate the LSTM model's performance on the validation dataset (X_seq, y_seq)
lstm_model.eval()
with torch.no_grad():
    val_outputs = lstm_model(X_seq)
    val_predictions = (val_outputs > 0.5).float()
    accuracy = (val_predictions == y_seq).float().mean().item()
    print(f"Validation Accuracy: {accuracy:.2f}")

Validation Accuracy: 1.00


In [22]:
import re

def predict_sentiment(text, model, word2idx, max_len):
    # Preprocess the input text
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    # Tokenize and encode
    tokens = text.split()
    idxs = [word2idx.get(word, 0) for word in tokens]  # Use 0 for unknown words
    # Pad or truncate to max_len
    if len(idxs) < max_len:
        idxs += [0] * (max_len - len(idxs))
    else:
        idxs = idxs[:max_len]
    input_tensor = torch.tensor(idxs).unsqueeze(0)  # Shape: (1, max_len)
    # Model prediction
    model.eval()
    with torch.no_grad():
        output = model(input_tensor)
        pred = (output > 0.5).item()
    return "Positive" if pred else "Negative"

# Example usage:
# print(predict_sentiment("I love PyTorch", lstm_model, word2idx, max_len))

In [23]:
# Example usage:
print(predict_sentiment("I love PyTorch", lstm_model, word2idx, max_len))

Positive


# Conclusion

# In this notebook, we explored the basics of PyTorch, including tensor operations, automatic differentiation, and building neural networks for both image and text data. 
# We demonstrated how to preprocess data, encode text, and train models for classification tasks using both simple and LSTM-based architectures.
# The practical examples on the MNIST dataset and sentiment analysis provided hands-on experience with data loading, model definition, training, and evaluation.
# With these foundational skills, you are now equipped to further explore deep learning applications using PyTorch for a variety of domains.